ssp:
  self_play:
    mission: "Improve assistant answers for reasoning, clarity, and faithfulness on product Q&A."
    domain_constraints:
      allowed_topics: ["product", "pricing", "shipping", "returns"]
      banned_topics: ["medical", "legal"]
    enabled: true
    batch_size: 8
    max_episode_length: 10
    temperature: 0.7
    verification_threshold: 0.85
    # tree
    M: 2
    N: 2
    L: 1
    scorer_name: 
      - sicql
      - tiny
      - hrm
    dimensions:
      - knowledge
      - clarity
      - reasoning
    use_zscore_intra: false
    use_zscore_inter: true
    value_alpha: 0.0
    prefer_non_buggy: true

    qmax:
      initial_difficulty: 0.3
      difficulty_step: 0.05
      max_difficulty: 0.95
      competence_window: 100

    curriculum:
      min_success_rate: 0.6
      max_failure_rate: 0.3
      difficulty_adjustment: 0.1

    snapshots:
      keep: 5
      update_interval: 50

    jitter:
      tick_interval: 2.0  # seconds
      sensory_channels:
        - vpm
        - scm
        - epistemic
      metabolic_rate: 0.8

    proposer:
      max_query_length: 512
      verification_depth: 3
      novelty_threshold: 0.7

    solver:
      search_depth: 5
      max_retries: 3
      reasoning_budget: 2048

    verifier:
      scorers: ["sicql", "tiny"]
      dimensions: [novelty, clarity, relevance, implementability, alignment]
      hrms:
        - name: coherence
          weight: 0.3
        - name: novelty
          weight: 0.2
        - name: causality
          weight: 0.25
        - name: consistency
          weight: 0.25
      min_evidence_count: 2
