# conf/scoring/llm_judge/default.yaml
name: llm_judge
model_type: llm
model_alias: LLM
display_name: LLM

dimension: quality

All right prompt_pair: prompts/eval/llm_judge_pair.jinja
prompt_single: prompts/eval/llm_judge_single.jinja

comparison_notes: ""

model:
  name: ollama/qwen3
  api_base: http://localhost:11434
  api_key: null
