pipeline_variants:
  cot:
    description: "Generates multiple chain-of-thought hypotheses using standard and DSPy agents, followed by ranking."
    stages:
      - name: cot_generator
        cls: stephanie.agents.cot_generator.ChainOfThoughtGeneratorAgent
        enabled: true
        iterations: 1
      - name: ranking
        cls: stephanie.agents.ranking.RankingAgent
        enabled: true
        iterations: 1
      - name: cot_dspy_generator
        cls: stephanie.agents.cot_dspy_generator.ChainOfThoughtDSPyGeneratorAgent
        enabled: true
        iterations: 1

  minimal:
    description: "A lightweight pipeline using a single generation agent for quick hypothesis output."
    stages:
      - name: generation
        cls: stephanie.agents.generation.GenerationAgent
        enabled: true
        iterations: 1


  search_arxiv:
    name: search_arxiv
    tag: "search_arxiv"
    description: "Search Arxiv for papers related to a goal"
    stages:
      - name: arxiv_search
        description: "Search Arxiv for papers related to the goal" 
        cls: stephanie.agents.knowledge.arxiv_search.ArxivSearchAgent
        enabled: true
        iterations: 1
      - name: document_loader
        description: "Load documents from the search results and summarize them"
        cls: stephanie.agents.knowledge.document_loader.DocumentLoaderAgent
        enabled: true
        iterations: 1
      - name: document_profiler
        description: "Profile the loaded documents to extract key sections"
        cls: stephanie.agents.knowledge.document_profiler.DocumentProfilerAgent
        enabled: true
        iterations: 1
      - name: paper_score
        description: "Score the papers based on their relevance and quality"
        cls: stephanie.agents.knowledge.paper_score.PaperScoreAgent
        enabled: true
        iterations: 1
      - name: knowledge_loader
        description: "Load knowledge from the scored papers into the system"
        cls: stephanie.agents.knowledge.knowledge_loader.KnowledgeLoaderAgent
        enabled: true
        iterations: 1
      - name: mrq_trainer
        description: "Build document pairs for training and evaluation" 
        cls: stephanie.agents.maintenance.mrq_trainer.MRQTrainerAgent 
        enabled: true
        iterations: 1
      - name: document_reward_scorer
        description: "Score the documents based on their relevance and quality"
        cls: stephanie.agents.knowledge.document_reward_scorer.DocumentRewardScorerAgent
        enabled: true
        iterations: 1