# stephanie/portfolio/diagnostics.py
"""Portfolio diagnostics (§25)."""
from __future__ import annotations

NO_ELIGIBLE_MODEL = "PORTFOLIO_NO_ELIGIBLE_MODEL"
BUDGET_EXCEEDED = "PORTFOLIO_BUDGET_EXCEEDED"
ROLE_UNFILLED = "PORTFOLIO_ROLE_UNFILLED"
INDEPENDENCE_VIOLATION = "PORTFOLIO_INDEPENDENCE_VIOLATION"
EXECUTION_FAILED = "PORTFOLIO_EXECUTION_FAILED"
EVALUATION_MISSING = "PORTFOLIO_EVALUATION_MISSING"
DISAGREEMENT_UNRESOLVED = "PORTFOLIO_DISAGREEMENT_UNRESOLVED"
VERIFICATION_FAILED = "PORTFOLIO_VERIFICATION_FAILED"
SYNTHESIS_FAILED = "PORTFOLIO_SYNTHESIS_FAILED"
CORRELATED_FAILURE = "PORTFOLIO_CORRELATED_FAILURE"
ZERO_MARGINAL_GAIN = "PORTFOLIO_ZERO_MARGINAL_GAIN"


class PortfolioDiagnostic(Exception):
    def __init__(self, code: str, message: str, context: dict | None = None):
        super().__init__(f"[{code}] {message}")
        self.code = code
        self.context = dict(context or {})
