# config/scorer/mrq/default.yaml
name: mrq
model_type: mrq
model_version: v1
evaluator: mrq
target_type: document
dimensions: 
  - alignment
  - clarity
  - implementability
  - novelty
  - relevance
