# Pulls in all scorer defaults in one shot.
# Tip: set package to "scorer" so each subconfig lands under scorer.*
# (only if those child configs don't already set package themselves)

defaults:
  - reward/default
  - ebt/default
  - hrm/default
  - knowledge/default
  # - epistemic_hrm/default
  - mrq/default
  - sicql/default
  - svm/default
  - tiny/default
  - contrastive_ranker/default
