services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: stephanie-dev-app   # ✅ add this line
    volumes:
      - ..:/workspace:cached
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/stephanie
    command: sleep infinity

  db:
    image: ankane/pgvector:latest   # Postgres with pgvector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stephanie
    ports:
      - "5432:5432"

networks:
  default:
    name: devcontainer_default