defaults:
  - _self_
  - db: postgres
  - plan_monitor: disabled
  - bus: nats   
  - logging/json_logger
  - mars/default
  - services/default
  - scorer: all  


  - agents/chat_mrq_trainer
  - agents/chat_sicql_trainer
  - agents/chat_hrm_trainer

embeddings:
  backend: hnet


goal:
  goal_text: I want to build an AI that can teach itself to solve complex problems better over time.
  goal_type: "tactical"
  goal_category: "meta_learning"
  focus_area: "self_improvement"
  strategy: "stepwise_decomposition"
  difficulty: "medium-high"
  expected_formats:
    - "symbolic_prompt_plan"
    - "stepwise_reasoning_trace"
    - "annotated_score_vector"

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

pipeline:
  name: chat training
  tag: chat_training
  description: "Uses chat history to train models. Different dynamics than traditional training."
  stages:
     - name: chat_mrq_trainer
       description: "Trains a MRQ model using chat conversations" 
       cls: stephanie.agents.maintenance.mrq_trainer.MRQTrainerAgent 
       enabled: false
       iterations: 1

     - name: chat_sicql_trainer
       description: "Trains a SICQL model using chat conversations"
       cls: stephanie.agents.maintenance.sicql_trainer.SICQLTrainerAgent
       enabled: true
       iterations: 1

     - name: chat_hrm_trainer
       description: "Train a HRM model to predict values usin chat conversation_turns"
       cls: stephanie.agents.maintenance.hrm_trainer.HRMTrainerAgent
       enabled: false
       iterations: 1

     - name: document_ebt_trainer
       description: "Train a model to predict document values based on EBT" 
       cls: stephanie.agents.maintenance.ebt_trainer.EBTTrainerAgent 
       enabled: false
       iterations: 1

     - name: rank_trainer
       description: "Train a ranker model using SICQL"
       cls: stephanie.agents.maintenance.rank_trainer.ContrastiveRankerTrainerAgent
       enabled: false
       iterations: 1

     - name: knowledge_loader
       description: "Load knowledge from the scored papers into the system"
       cls: stephanie.agents.knowledge.knowledge_loader.KnowledgeLoaderAgent
       enabled: false
       iterations: 1

     - name: scorable_embedding_backfill
       description: "Backfill document embeddings for existing documents"
       cls: stephanie.agents.maintenance.scorable_embedding_backfill.DocumentEmbeddingBackfillAgent
       enabled: false
       iterations: 1

     - name: knowledge_db_loader
       description: "Load knowledge from the database into the system"
       cls: stephanie.agents.knowledge.knowledge_db_loader.KnowledgeDBLoaderAgent
       enabled: false
       iterations: 1

     - name: document_llm_inference
       description: "Infer LLM scores for documents" 
       cls: stephanie.agents.inference.llm_inference.LLMInferenceAgent 
       enabled: false
       iterations: 1

     - name: document_mrq_inference
       description: "Infer MRQ scores for documents" 
       cls: stephanie.agents.inference.mrq_inference.MRQInferenceAgent 
       enabled: false
       iterations: 
       
     - name: document_svm_inference
       description: "Infer SVM scores for documents" 
       cls: stephanie.agents.inference.svm_inference.SVMInferenceAgent
       enabled: false
       iterations: 
       
     - name: document_ebt_inference
       description: "Infer EBT scores for documents" 
       cls: stephanie.agents.inference.ebt_inference.EBTInferenceAgent 
       enabled: false
       iterations: 
       
     - name: document_reward_scorer
       description: "Score the documents based on their relevance and quality"
       cls: stephanie.agents.knowledge.document_reward_scorer.DocumentRewardScorerAgent
       enabled: false
       iterations: 1

     - name: scorer
       description: "Score the documents based on various criteria"
       cls: stephanie.agents.scorer.ScorerAgent
       enabled: false
       iterations: 1