# config/compiler.yaml
defaults:
  - _self_
  - db: postgres
  - plan_monitor: disabled
  - bus: nats   
  - logging/json_logger
  - mars/default
  - services/default
  - scorer: all  

  - agents/related
  - agents/prompt_compiler


goal:
  goal_text: >
    Break down the question "How can AI systems become better at asking questions?"
    into a step-by-step reasoning plan using symbolic prompts that reflect dimensions
    like curiosity, relevance, and generalization. Each step should be explainable,
    reusable, and scored individually.
  goal_type: tactical
  goal_category: meta_reasoning
  focus_area: question_generation
  strategy: stepwise_decomposition
  difficulty: medium
  expected_formats:
    - symbolic_prompt_plan
    - stepwise_reasoning_trace
    - annotated_score_vector


paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports


embeddings:
  backend: hnet

pipeline:
  name: prompt_compiler
  description: "Compile a prompt and generate the best possible solution using Agenting tree Search"
  stages:
     - name: related
       cls: stephanie.agents.related.RelatedAgent
       enabled: true
       iterations: 1
     - name: prompt_compiler
       cls: stephanie.agents.prompt_compiler.PromptCompilerAgent
       enabled: true
       iterations: 1
