# config/config.yaml
defaults:
  - _self_
  - db: postgres
  - plan_monitor: disabled
  - scoring/service/default
  - logging/json_logger
  - mars/default

  - scorer: all  

  - agents/literature
  - agents/literature_ranking
  - agents/prompt_tuning
  - agents/generation
  - agents/refiner
  - agents/review
  - agents/reflection
  - agents/ranking
  - agents/evolution
  - agents/meta_review
  - agents/proximity
  - agents/sharpening
  - agents/judge
  - agents/lookahead
  - agents/symbolic_optimizer
  - agents/cot_generator
  - agents/cot_dspy_generator
  - agents/supervisor
  - logging/json_logger

# The goal of the pipeline, e.g., "Generate a hypothesis about the impact of climate change on biodiversity."
# This is a placeholder and should be replaced with the actual goal.
goal: 
  goal_text: "Will AI ever be able to reprogram itself?"
  goal_type: research # Options: math, science, commonsense, factoid, ethical, policy, planning, creative, other, research

dynamic:
  name: lookahead
  enabled: true
  cls: stephanie.agents.lookahead.LookaheadAgent

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"


embeddings:
  model: "mxbai-embed-large"
  dimension: 1024
  endpoint: "http://localhost:11434/api/embeddings"

pipeline:
  name: default_pipeline
  description: "Default hypothesis generation and refinement pipeline"
  stages:
     - name: generation
       cls: stephanie.agents.generation.GenerationAgent
       enabled: true
       iterations: 1
