jitter_v1# conf/jitter_v1.yaml
tick_interval: 1.0
subjects:
  telemetry: "arena.jitter.telemetry"
  events:    "arena.jitter.events"
  death:     "arena.jitter.death"
membrane:
  initial_thickness: 0.8
energy:
  initial_cognitive: 50
  initial_metabolic: 50
  initial_reserve:   20
homeostasis:
  energy_setpoint:    1.0
  boundary_setpoint:  0.8
  diversity_setpoint: 0.7
reproduction:
  ready_threshold: 50.0
  mutation_rate:   0.05   # canonical
  transfer_rate:   0.30   # canonical
