# config/memento.yaml
defaults:
  - _self_
  - db: postgres
  - plan_monitor: disabled
  - scoring/service/default
  - logging/json_logger
  - mars/default

  - scorer: all  


  - agents/arxiv_search
  - agents/modular_memento
  - agents/memento
  - agents/generation
  - agents/cbr_dspy
  - agents/cartridge
  - agents/document_loader
  - agents/document_profiler
  - agents/hrm_trainer
  - agents/document_reward_scorer
  - agents/icl_reasoning
  - agents/knowledge_loader
  - agents/planner_reuse
  - agents/planner_revise
  - agents/knowledge_db_loader
  - agents/pipeline_judge
  - agents/paper_score
  - agents/agent_scorer
  - agents/plan_trace_scorer
  - logging/json_logger

embeddings:
  backend: hnet

goal:
  goal_text: >
      You are an expert in reasoning systems and knowledge extraction.  
      I will provide you with one or more documents.  

      Case-Based Reasoning (CBR) is an approach where a system learns by remembering past cases, retrieving the most similar one for a new problem, adapting it to the current context, and revising the outcome. For example, if the system previously succeeded in using Agent A for document summarization under similar goals, it can try Agent A again for a new summarization task and adapt based on feedback.

      Your task is:

      **Extract Strong Hypotheses**  
      - Review the documents carefully and extract **1–3 strong hypotheses** that relate directly to the application of Case-Based Reasoning (CBR).  
      - A strong hypothesis is one that is **clear, testable, and actionable** towards building a self-improving system.  
      - Focus on hypotheses that would help improve **pipeline execution, agent scoring, or knowledge reuse**.  
      - Keep your output **concise and focused**.  

      ✅ Example of a good hypothesis:  
      "If each execution step in the pipeline is stored as a case and scored, then similar future steps can be retrieved and reused, improving decision quality over time."  

      **Output Format**  
      Use the following structure in your response:

      ---
      ## Score [0–100]  
      [Your confidence in the quality and relevance of the hypotheses]

      ## Rationale  
      [Brief explanation of why these hypotheses are strong and how they connect to CBR]

      ## Strong Hypotheses  
      - Hypothesis 1: ...  
      - Hypothesis 2: ...  


  goal_type: "strategic"
  goal_category: "meta_reasoning"
  focus_area: "case_based_learning"
  strategy: "retrieve_reuse_revise_retain"
  difficulty: "high"
  expected_formats:
    - "case_trace"
    - "scorable_rankings"
    - "revised_plan"
    - "retained_cartridge"

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

web_search:
  engine: "searxng"
  instance_url: "http://localhost:8080"

pipeline:
  name: cbr
  tag: cbr
  description: >
    Implementation of the Case-Based Reasoning (CBR) framework from the 
    Memento paper (https://arxiv.org/pdf/2508.16153).
    This pipeline demonstrates the full CBR loop — retrieve, reuse, revise, retain —
    by grounding reasoning in past cases (PlanTraces, evaluations, scorables),
    adapting them to new tasks, and storing new cases for continual self-improvement.
    To test we are using various agents for hypothesis generation and testing.
  stages:
     - name: arxiv_search
       agent_role: retrieve
       description: "📥 Retrieve: search Arxiv for candidate documents (knowledge cases)"
       cls: stephanie.agents.knowledge.arxiv_search.ArxivSearchAgent
       enabled: false
       iterations: 1

     - name: document_loader
       description: "Load and summarize candidate documents"
       cls: stephanie.agents.knowledge.document_loader.DocumentLoaderAgent
       enabled: false
       iterations: 1

     - name: document_profiler
       description: "Profile documents into structured sections for reuse"
       cls: stephanie.agents.knowledge.document_profiler.DocumentProfilerAgent
       enabled: false
       iterations: 1

     - name: knowledge_loader
       agent_role: revise
       description: "Revise: integrate new evidence into Stephanie’s knowledge base"
       cls: stephanie.agents.knowledge.knowledge_loader.KnowledgeLoaderAgent
       enabled: false
       iterations: 1

     - name: knowledge_db_loader
       description: "Load prior retained knowledge from the database for retrieval"
       cls: stephanie.agents.knowledge.knowledge_db_loader.KnowledgeDBLoaderAgent
       enabled: true
       iterations: 1    

     - name: cbr_dspy
       description: "Generate hypotheses from documents using a dspy process"
       cls: stephanie.agents.dspy.cbr_dspy.CBRDSPyAgent
       enabled: false
       iterations: 1    

     - name: generation
       description: "Generate new candidate documents based on existing knowledge"
       cls: stephanie.agents.generation.GenerationAgent
       enabled: false
       iterations: 1

     - name: memento
       description: "Generate hypotheses from documents using the Memento framework"
       cls: stephanie.agents.dspy.memento.MementoAgent
       enabled: false
       iterations: 1

     - name: modular_memento
       description: "Generate hypotheses from documents using the Modular Memento framework"
       cls: stephanie.agents.dspy.modular_memento.ModularMementoAgent
       enabled: true
       iterations: 1

     - name: paper_score
       description: "Evaluate case quality: relevance, novelty, clarity"
       cls: stephanie.agents.knowledge.paper_score.PaperScoreAgent
       enabled: false
       iterations: 1

     # HRM Training if you have specific documents you may want to retrain the model Don't understand
     - name: hrm_trainer
       description: "Train a model to predict document values based on HRM"
       cls: stephanie.agents.maintenance.hrm_trainer.HRMTrainerAgent
       enabled: false
       iterations: 1

     - name: planner_reuse
       agent_role: reuse
       description: "♻️ Reuse: adapt past PlanTraces and evaluations to the current goal"
       cls: stephanie.agents.knowledge.planner_reuse.PlannerReuseAgent
       enabled: false
       iterations: 1

     - name: planner_revise
       agent_role: revise
       description: "🔀 Revise: improve candidate plans based on feedback"
       cls: stephanie.agents.knowledge.planner_revise.PlannerReviseAgent
       enabled: false
       iterations: 1

     - name: document_reward_scorer
       description: "Refine document scores using reward models (optional)"
       cls: stephanie.agents.knowledge.document_reward_scorer.DocumentRewardScorerAgent
       enabled: false
       iterations: 1

     - name: cartridge
       agent_role: retain
       description: "🧩 Retain: generate reusable cartridges (belief units) from revised knowledge"
       cls: stephanie.agents.knowledge.cartridge.CartridgeAgent
       enabled: false
       iterations: 1

     - name: icl_reasoning
       description: "Apply in-context reasoning to test retained knowledge against the goal"
       cls: stephanie.agents.icl_reasoning.ICLReasoningAgent
       enabled: false
       iterations: 1
