# config/papers.yaml
defaults:
  - _self_
  - db: postgres
  - plan_monitor: disabled

  - logging/json_logger
  - mars/default

  - scorer: all  

  - agents/survey
  - agents/search_orchestrator
  - agents/knowledge_loader
  - agents/document_loader
  - agents/paper_score
  - agents/literature
  - agents/literature_ranking
  - agents/document_profiler
  - agents/generation
  - agents/paper_score
  - logging/json_logger

post_judgment:
  name: pipeline_judge
  enabled: false
  cls: stephanie.agents.pipeline_judge.PipelineJudgeAgent

paths:
  prompts: ${hydra:runtime.cwd}/prompts

report:
  generate_report: true
  path: ${hydra:runtime.cwd}/reports

embeddings:
  backend: hnet

goal:
  # goal_text: "https://arxiv.org/pdf/2506.05070"
  # goal_text: "https://arxiv.org/pdf/2505.15143"
  goal_text: "2106.09685"
  # goal_text: "https://arxiv.org/abs/2305.14314"
  
  # goal_type: "similar_papers"
  goal_type: "arxiv_search"
  
  focus_area: "AI research"

pipeline:
  name: paper_import_pipeline
  tag: "paper_import_pipeline"
  description: "Import papers score and save them"
  stages:
     - name: survey
       cls: stephanie.agents.knowledge.survey.SurveyAgent
       enabled: true
       iterations: 1
     - name: search_orchestrator
       cls: stephanie.agents.knowledge.search_orchestrator.SearchOrchestratorAgent
       enabled: true
       iterations: 1
     - name: document_loader
       cls: stephanie.agents.knowledge.document_loader.DocumentLoaderAgent
       enabled: true
       iterations: 1
     - name: document_profiler
       cls: stephanie.agents.knowledge.document_profiler.DocumentProfilerAgent
       enabled: true
       iterations: 1
     - name: paper_score
       cls: stephanie.agents.knowledge.paper_score.PaperScoreAgent
       enabled: true
       iterations: 1
     - name: knowledge_loader
       cls: stephanie.agents.knowledge.knowledge_loader.KnowledgeLoaderAgent
       enabled: true
       iterations: 1
