# config/scoring/service/default.yaml
enabled: true
create_missing_evaluations: true
enabled_scorers:
  - epistemic_hrm
  - hrm
  - sicql
  - svm
  - mrq
  - knowledge
  - ebt
  - contrastive_ranker
  - reward
