agent_scorer:
  name: agent_scorer
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false

  include_mars: true
  enabled_scorers:
    - hrm
    - sicql
    - svm
    - mrq
    - ebt
    - contrastive_ranker

  include_ranking: true
  rank_top_k: 5

  dimensions: 
    - alignment
    - clarity
    - implementability
    - novelty
    - relevance


  dimension_config:
    alignment:
      scale: "0-100"
      trust_references: ["llm"]
      expected_variance: 0.15
    clarity:
      scale: "0-100"
      trust_references: ["llm"]
      expected_variance: 0.15
    implementability:
      scale: "0-100"
      trust_references: ["llm"]
      expected_variance: 0.15
    novelty:
      scale: "0-100"
      trust_references: ["llm"]
      expected_variance: 0.15
    relevance:
      scale: "0-100"
      trust_references: ["llm"]
      expected_variance: 0.15

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: agent_scorer
  prompt_mode: file
  prompt_file: agent_scorer.txt