cbr_dspy:
  name: cbr_dspy
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: cbr_dspy
  prompt_mode: file
  prompt_file: cbr_dspy.txt