chat_hrm_trainer:
  name: chat_hrm_trainer
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false

  dimensions: 
    - reasoning
    - knowledge
    - clarity
    - faithfulness
    - coverage

  hrm: 
    name: hrm
    model_type: hrm
    target_type: conversation_turn
    model_path: "${hydra:runtime.cwd}/models"
    version: v1
    h_dim: 256
    l_dim: 128
    output_dim: 1
    n_cycles: 4
    t_steps: 4
    lr: 0.001
    batch_size: 32
    epochs: 10

  sicql:
    name: chat_hrm_sicql
    model_type: sicql
    evaluator: sicql
    target_type: conversation_turn
    dimensions: 
      - reasoning
      - knowledge
      - clarity
      - faithfulness
      - coverage

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  
  input_keys: [goal, hypotheses]
  input_key: documents
  
  output_key: hrm_trainer
  prompt_mode: file
  prompt_file: hrm_trainer.txt