chat_to_casebook:
  name: chat_to_casebook
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: chat_to_casebook
  prompt_mode: file
  prompt_file: chat_to_casebook.txt