# configs/agents/cot_long_sicql_generator.yaml

cot_long_sicql_generator:
  name: cot_long_sicql_generator
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false

  evaluator: llm         #(mrq or llm)  may not be enough items fo mrq
  evaluator_prompt_file: evaluation.txt
  evaluator_model:
    name: ollama/phi3
    api_base: http://localhost:11434
    api_key: null

  analysis_model:
    name: ollama/llama3.2
    api_base: http://localhost:11434
    api_key: null

  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null

  input_key: hypotheses   # add nodes
  output_key: hypotheses
  prompt_mode: file
  prompt_file: generate_long_cot.txt
  pattern_prompt_file: cot_pattern.txt
  use_memory_for_fast_prompts: true

  remove_think: false # we require "thinking" part of the prompt

  device: cpu # How many epochs to wait after no improvement
  limit: 1000 # max training data
  epochs: 20  # how much to train
  patience: 3  # How many epochs to wait after no improvement
  min_delta: 0.0001  # Minimum change in loss to qualify as improvement
  log_results: true # save results to database
  save_improved: true # save improved prompts and hypotheses

  rubrics:
    - dimension: "Strategy Orientation"
      rubric: "Does the reasoning proceed in a hypothesis-first (top-down) or data-first (bottom-up) manner?"
      options: ["Top-Down", "Bottom-Up"]
      enabled: true
    - dimension: "Inference Style"
      rubric: "Is the reasoning based on deductive logic from known facts, or analogical reasoning across domains?"
      options: ["Deductive", "Analogical"]
      enabled: true
    - dimension: "Exploration Breadth"
      rubric: "Does the reasoning consider only one main path (greedy) or explore multiple possibilities before deciding (exhaustive)?"
      options: ["Greedy", "Exhaustive"]
      enabled: true
    - dimension: "Reasoning Depth"
      rubric: "Is the reasoning shallow and surface-level, or deep and multi-step with recursive analysis?"
      options: ["Shallow", "Deep"]
      enabled: true
    - dimension: "Evidence Use"
      rubric: "Is the reasoning guided primarily by prior beliefs and assumptions, or by explicit evidence and data?"
      options: ["Belief-Driven", "Data-Driven"]
      enabled: true
    - dimension: "Certainty Expression"
      rubric: "Does the reasoning assert answers with confidence, or express uncertainty and hedging?"
      options: ["Confident", "Tentative"]
      enabled: true
    - dimension: "Planning Approach"
      rubric: "Does the reasoning follow a predefined plan from the start, or adaptively revise as new steps unfold?"
      options: ["Planned", "Adaptive"]
      enabled: false
    - dimension: "Goal Focus"
      rubric: "Is the reasoning focused directly on answering the question, or does it explore adjacent ideas and tangents?"
      options: ["Focused", "Exploratory"]
      enabled: false
    - dimension: "Perspective Use"
      rubric: "Does the reasoning rely on a single viewpoint, or synthesize multiple perspectives or stakeholder views?"
      options: ["Single-Perspective", "Multi-Perspective"]
      enabled: false
    - dimension: "Abstraction Level"
      rubric: "Does the reasoning remain at a high abstract level, or include concrete examples and specific details?"
      options: ["Abstract", "Concrete"]
      enabled: false
    - dimension: "Error Handling"
      rubric: "Does the reasoning acknowledge and correct possible errors, or proceed as if all steps are valid?"
      options: ["Self-Correcting", "Linear"]
      enabled: false
    - dimension: "Generative vs Discriminative"
      rubric: "Does the reasoning create multiple hypotheses and choose among them, or verify a single leading idea?"
      options: ["Generative", "Discriminative"]
      enabled: false
    - dimension: "Time Orientation"
      rubric: "Does the reasoning emphasize past causes or future consequences?"
      options: ["Retrospective", "Prospective"]
      enabled: false
    - dimension: "Narrative Style"
      rubric: "Is the reasoning framed as a story or scenario, or structured logically and factually?"
      options: ["Narrative", "Analytical"]
      enabled: false
