# configs/agents/literature.yaml

literature:
  name: literature
  enabled: true
  save_context: true
  skip_if_completed: false
  strategy: query_and_summarize
  max_results: 5
  model:
    name: ollama_chat/qwen3
    api_base: http://localhost:11434
    api_key: null
  save_prompt: false
  add_prompt_to_history: false # prompt will be very large will include text of pages
  prompt_mode: file
  prompt_file: query.txt
  parse_prompt: parse.txt
  input_key: goal
  output_key: literature
  preferences:
    - goal_consistency
    - factual
    - reliable_source
    - simplicity
  web_search:
    engine: "searxng"
    instance_url: "http://localhost:8080"
    max_results: 20
  