ner_retriever:
  name: ner_retriever
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: ner_retriever
  prompt_mode: file
  prompt_file: ner_retriever.txt