sot_v01_agent:
  name: sot_v01_agent
  enabled: true
  save_prompt: true
  save_context: false
  skip_if_completed: false
  model:
    name: ollama/qwen3
    api_base: http://localhost:11434
    api_key: null
  input_keys: ["goal", "hypotheses"]
  input_key: documents
  output_key: sot_v01_agent
  prompt_mode: file
  prompt_file: sot_v01_agent.txt